### ISSUE TITLE
Question: how to set gid?

### ISSUE THREAD

**Issue by davidjtferguson** [dganzella/chickenTiledLoader#1]
Hello, just wanted to ask a question about Gid usage that was added.

I can see in your example exported map your character has a Gid associated with it that allows you to use the getTileImageByGid(...) function.

I'm trying to figure out how to set this. Is there some option I am missing in Tiled that sets this for the export? Or did you manually set this in the tmj file after export, or write some code to set it?

Thanks.

**Comment by dganzella** [comment]
@davidjtferguson  the GID is defined by the TiledMap engine itself!

![image](https://github.com/user-attachments/assets/45bd17cd-2c21-4be1-a4fd-d2770a08d61d)

Its the ID of the tile.

There is a special object called "Tile" object

![image](https://github.com/user-attachments/assets/e1ad9ae2-87b5-4a95-99d4-3e43e2a5d3ae)

That allows you to spawn an object with a GID (Tile ID) associated with it :)

![image](https://github.com/user-attachments/assets/2bc224c5-483d-4a63-9013-00570d23f9c3)

but not all obejcts have it.

Thats why on TMJObject, gid is optional -- some have, some dont

**Comment by davidjtferguson** [comment]
Aaahh, okay, thank you. I'd created a rectangle object and named it Char, instead of a tile object. Created a tile object and it exports with the gid now. That makes sense since I hadn't associated the tile with the object in any way before... Obvious in hindsight! Thanks a bunch!
